# -*- coding: utf-8 -*-
"""parse txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5LJRfOnOqI_X5nVOfPKK6tzrmj5vd2h
"""

import requests

file1 = open("/content/my_preds.txt","r")
line= ""
for i in range(0,3):
  line = file1.readline()
first_word = line.split()[0]

query = first_word.replace('_',' ')
api_key = "sinnv6OHnqg26bIlTQwp0Maf5InFD1AM9LPdwaE2"

url = "https://api.nal.usda.gov/fdc/v1/foods/search"
params = {
    "api_key": api_key,
    "query": query,
    "pageSize": 1
}

response = requests.get(url, params=params)
data = response.json()

if data["foods"]:
    food = data["foods"][0]
    print("Description:", food["description"])
    fdc_id = food["fdcId"]
    details_url = f"https://api.nal.usda.gov/fdc/v1/food/{fdc_id}"
    params = {"api_key": api_key}
    details_response = requests.get(details_url, params=params)
    details_data = details_response.json()
    for nutrient in details_data["foodNutrients"]:
        name = nutrient["nutrient"]["name"]
        value = nutrient.get("amount", "N/A")
        unit = nutrient["nutrient"].get("unitName", "")
        print(f"{name}: {value} {unit}")
else:
    print("No results found.")

